#!/bin/bash

if [ "$2" == "" ]
then
    if ["$1" == ""]
    then
        ./cfl-core
    else
        FILENAME="${1%.*}"
        ./cfl-core $@ &> $FILENAME.ll
        llvm-as -o $FILENAME $FILENAME.ll
        chmod +x $FILENAME
    fi
else
    if [ "$1" == "-jit" ]
    then
        FILENAME="${2%.*}"
        ./cfl-core $2 &> $FILENAME.ll
        lli $FILENAME.ll
    else
        ./cfl-core $@
    fi
fi
