#!/bin/bash

if [ -e "cfl-core" ]
then
    if [ "$2" == "" ]
    then
        if [ "$1" == "" ]
        then
            ./cfl-core
        else
            FILENAME="${1%.*}"
            ./cfl-core $@ 2> $FILENAME.ll
            if [ $? != 0 ]
            then
                cat $FILENAME.ll
                rm $FILENAME.ll
                exit 1
            fi
            opt $FILENAME.ll > $FILENAME.bc
            rm $FILENAME.ll
            llc $FILENAME.bc
            rm $FILENAME.bc
            clang -o $FILENAME $FILENAME.s
            rm $FILENAME.s
        fi
    else
        if [ "$1" == "-ll" ]
        then
            ./cfl-core $2 2>&1
        else
            if [ "$1" == "-asm" ]
            then
                FILENAME="${2%.*}"
                ./cfl-core $2 &> $FILENAME.ll
                if [ $? != 0 ]
                then
                    cat $FILENAME.ll
                    rm $FILENAME.ll
                    exit 1
                fi
                cat $FILENAME.ll | llc
                rm $FILENAME.ll
            else
                if [ "$1" == "-jit" ]
                then
                    FILENAME="${2%.*}"
                    ./cfl-core $2 &> $FILENAME.ll
                    if [ $? != 0 ]
                    then
                        cat $FILENAME.ll
                        rm $FILENAME.ll
                        exit 1
                    fi
                    lli $FILENAME.ll
                    rm $FILENAME.ll
                else
                    ./cfl-core $@
                fi
            fi
        fi
    fi
else
    if [ -e "cfl-core-c" ]
    then
        ./cfl-core-c $@
    else
        echo "cfl has not been built. You must make it."
    fi
fi
