#!/bin/bash

if [ -e "cfl-core" ]
then
    if [ "$2" == "" ]
    then
        if [ "$1" == "" ]
        then
            ./cfl-core
        else
            FILENAME="${1%.*}"
            ./cfl-core $@ &> $FILENAME.ll
            llc $FILENAME.ll
            clang -o $FILENAME $FILENAME.s
        fi
    else
        if [ "$1" == "-jit" ]
        then
            FILENAME="${2%.*}"
            ./cfl-core $2 &> $FILENAME.ll
            lli $FILENAME.ll
        else
            ./cfl-core $@
        fi
    fi
else
    if [ -e "cfl-core-c" ]
    then
        ./cfl-core-c $@
    else
        echo "cfl has not been built. You must make it."
    fi
fi
