#!/usr/bin/python

import os
import subprocess

def call(command):
  subprocess.call(command, shell = True)

def run_tests():
  print 'Running tests...'
  passed_tests = 0
  failed_tests = 0
  for f in os.listdir('tests/'):
    if f.endswith('.cfl'):
      in_file = 'tests/' + f
      result_file = in_file + '.out'
      out_file = f + '.out'
      command = './cfl -eval ' + in_file + ' &> ' + out_file
      call(command)
      with open(out_file, 'r') as out:
        out_contents = out.read()
      with open(result_file, 'r') as result:
        result_contents = result.read()
      if out_contents != result_contents:
        failed_tests += 1
        print '\033[91mERROR:   Test ' + in_file + ' failed!\033[0m'
      else:
        passed_tests += 1
        print '\033[92mSUCCESS: Test ' + in_file + ' passed.\033[0m'
      call('rm ' + out_file)
  print 'Done with tests.'
  total_tests = passed_tests + failed_tests
  print str(passed_tests) + ' tests passed, and ' + \
        str(failed_tests) + ' failed; total: ' + str(total_tests)

run_tests()
